#!/bin/bash
# Developed by Sabelvai
clear
echo "Simple SSD Live Check"
echo "Developed by Sabelvai"
echo "https://github.com/Sabelvai"
echo " "
logicalSectorWritten=$(sudo smartctl -x /dev/sda | grep 0x018)
sectorSize=$(sudo smartctl -x /dev/sda | grep "^Sector Size:")
echo $logicalSectorWritten
echo $sectorSize
echo " "
read -p "Enter parameter 4 Logical Sectors Written " logicalSectorWrittenAnswear
read -p "Enter Sector Size " sectorSizeAnswear
echo " "
x=$((logicalSectorWrittenAnswear*sectorSizeAnswear/1024/1024/1024))
y=300
echo "$x GB of rewrites"
if ((x>y))
then
GREEN="32"
BOLDGREEN="\e[1;${GREEN}m"
ENDCOLOR="\e[0m"
echo -e "${BOLDGREEN}YOUR SSD WILL LIVE${ENDCOLOR}"
else
RED="\e[31m"
ENDCOLOR="\e[0m"
echo -e "${RED}YOUR SSD IS GOING TO DIE!!!${ENDCOLOR}"
fi